language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

before_install:
  - composer self-update

install:
    - composer install --prefer-dist --optimize-autoloader --no-interaction

script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --coverage-clover=coverage.clover
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then CODECLIMATE_REPO_TOKEN=3c42c0270afce27ee1825152b71c2f987bfbd04771c0d4f0b40589252f3efa01 ./vendor/bin/test-reporter; fi
