language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - composer self-update

install:
    - composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction --quiet

script: phpunit --configuration phpunit.xml --coverage-text
