language: php

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm
        - php: nightly

before_install:
  - composer self-update

install:
    - composer install --prefer-dist --optimize-autoloader --no-interaction

script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --coverage-clover=coverage.clover
